### ISSUE TITLE
HSYNC/VSYNCの極性？

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#10]
.iVSYNC_POL(1'b1), .iHSYNC_POL(1'b1),というのが追加されているようですが、HSYNC/VSYNCの極性を指定できるようにしていただきましたか？（確認）

**Comment by watari3** [comment]
出力側のタイミング及び制御信号はTMG_CTRL.vにて正論理で生成されています。
最終段出力に当たるOUT_VIDEO_DATA.vのiVSYNC_POL, iHSYNC_POLにて極性を反転できるようになっています。
0は極性反転なし、1は極性反転あり、となります。
