### ISSUE TITLE
CLKGEN_MMCM関連のエラー

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#11]
generate_IP_design_CLKGEN_MMCM.tclに不具合あり。
修正が必要。

**Comment by akita11** [comment]
いつごろ修正fixできそうですか？

**Comment by watari3** [comment]
３箇所の"#"を削除。
これで問題が改善するか確認願います。

**Comment by watari3** [comment]
こちらの環境では正しく動作出来ていそうです。

発生原因として推測されている「FPGA/project_1/project_1.srcs/source_1/ip/に各IPディレクトリがない」についてこちらでも調査いたします。

なおこちらの認識ではgenerate_IP_design_CLKGEN_MMCM.tclの26～27行目にて必要なファイルが生成及びプロジェクトへ登録されると思っています。

**Comment by akita11** [comment]
新たにpullしたものに対して、tclで生成すると、そのファイルはすでにプロジェクトに含まれる、というエラーがでます。
以下、順に。

まず新たにpullし、プロジェクトを開くと以下のメッセージが出ます。
https://gyazo.com/1e64ba4aa27a1dc875a001818c405b9b
CLKGEN_MMCMがない、というのがcritical warningですね。

この状態で、プロジェクトのファイル構成は、こんな感じです。
https://gyazo.com/df7e7e2cf7004ffaeb85bd6d08659965
3つのIPが、？になっています。

その後、generate_IP_design_CLKGEN_MMCM.tclをsourceした結果がこちらです。
https://gyazo.com/042aa9aaa113823d04b9588c1e4caf3e
既にプロジェクトに含まれるのでskipされています。

本来は、この段階で3つのIPをtclスクリプトで生成すれば、*.xciが作成され、
プロジェクトのファイル構成にある？が解消されるはず、なのですが、
これはどういうことでしょうか。

**Comment by akita11** [comment]
最新版（今朝の時点で）を新たにpullしてプロジェクトを開いたあとでtclで生成すると、やはり同様のエラーが出ます。
[![https://gyazo.com/0061a41986c9f106880b0f302a9da286](https://gyazo.com/0061a41986c9f106880b0f302a9da286/raw)](https://gyazo.com/0061a41986c9f106880b0f302a9da286)

**Comment by watari3** [comment]
備忘録を兼ねて記載します。

抜本的な対策が必要と思われる。
Linux環境下で何種類かのテストコードを用意しテストすること。

tclベースの合成＆配置配線スクリプトを実行するとCLK周りでFailする。
CLK信号の扱いについて考察する必要あり。

**Comment by akita11** [comment]
これは優先度低めでいいですよね。回路のデバッグを優先で。

**Comment by watari3** [comment]
本件
C:\work\EyeTracker\designs\FPGA\project_1\project_1.ip_user_files\ip
ディレクトリ内にCLKGEN_MMCMディレクトリがなく
C:\work\EyeTracker\designs\FPGA\project_1\project_1.srcs\sources_1\ip\CLKGEN_MMCM.xcix
ファイルが存在している場合に発生する。

C:\work\EyeTracker\designs\FPGA\project_1\project_1.srcs\sources_1\ip\CLKGEN_MMCM.xcixを削除後、vivado上からIP SourcesのCLKGEN_MMCMを削除し再度該当tclファイルを実行することで問題解決。

上記対応で問題が解決することを確認済み。
以上より本件closeします。
