### ISSUE TITLE
Rawデータのbit精度

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#14]
内蔵SRAMのビット制約(オリジナルデザインSpartan6縛り)により現状カメラ入力の上位5bitを保持しています。

Kintex-7 160Tに変更になったので多少(1bit程度?)は追加できると思われますが、やってみないとわからない&ILAの完全削除が必須です。

下記のどれを選択し実装すればよいでしょうか。
ご意見をいただけないでしょうか。

a) 現行デザインのまま上位5bitのみを保持 (ILAはそのまま)
b) 上位3bitを捨てて下位5bitのみを保持 (ILAはそのまま)
c) 上位3bitを捨てて下位5bitを3bitシフト(８倍)して保持 (ILAはそのまま)
d) ILAを完全削除し上位6bitを保持 (ILAを削除。失敗の可能性あり)
e) その他

**Comment by akita11** [comment]
現行のまま上位5bit保持の(a)でお願いします

>

**Comment by watari3** [comment]
a)でデザイン作成＆デバッグ済み。
