### ISSUE TITLE
重心処理に使用するしきい値の仕様

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#16]
仕様の確認及びRTLの修正が必要

【仕様】
誤) カメラからの入力データがしきい値を超えたら1とする
正) カメラからの入力データがしきい値を下回ったら1とする

【修正】
修正前)
CLctrl.vの115, 116行目
                    oMEMIN_0[i  ] <= (iDATA_L>iTHRESHOLD) ? 1'b1: oMEMIN_0[i  ];
                    oMEMIN_0[i+1] <= (iDATA_R>iTHRESHOLD) ? 1'b1: oMEMIN_0[i+1];
修正後)
CLctrl.vの115, 116行目
                    oMEMIN_0[i  ] <= (iDATA_L<iTHRESHOLD) ? 1'b1: oMEMIN_0[i  ];
                    oMEMIN_0[i+1] <= (iDATA_R<iTHRESHOLD) ? 1'b1: oMEMIN_0[i+1];

**Comment by akita11** [comment]
この「正」のほうが正しい仕様です。

**Comment by watari3** [comment]
仕様の間違いを認識＆修正されていることを確認しましたので本件closeします。
