### ISSUE TITLE
UARTによる内部レジスタアクセス

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#17]
デバッグ・設定値変更のためにUARTによる内部レジスタアクセス機能を検討する。

とりあえずは仕様検討のみ。

【仕様案】
- Plan 1
・内部レジスタへの書き込み
Input : "wr 4桁のアドレス(2バイト/16進アスキーキャラ) 4桁のデータ(2バイト/16進アスキーキャラ)"+"lf"
Output : コマンドが認識されたら"OK"+"lf"、認識されなかったら"NG"+"lf"を出力
・内部レジスタの読み込み
Input : "rd 4桁のアドレス(2バイト/16進アスキーキャラ)"+"lf"
Output : コマンドが認識されたら"リードした4桁のデータ(2バイト/16進アスキーキャラ)"+"lf"+"OK"+"lf"、認識されなかったら"NG"+"lf"を出力

- Plan 2
Microblaze(ソフトCPU)にてUART処理を実装する。

**Comment by watari3** [comment]
feature/support_host_if ブランチにてHost IFを実装していく。

**Comment by watari3** [comment]
下記仕様で(別プロジェクトで)実装、Sim完了。移植すれば使用可能。

【仕様】
- 内部レジスタへの書き込み
Input: "wr 4桁のアドレス(2バイト/16進アスキーキャラクタ) 2桁のデータ(1バイト/16進アスキーキャラクタ)"+"lf"
Output: コマンドが認識されたら"OK"+"lf"、認識されなかったら"NG"+"lf"を出力
- 内部レジスタへの書き込み
Input: "rd 4桁のアドレス(2バイト/16進アスキーキャラクタ)"+"lf"
Output: コマンドが認識されたら"OK"+"lf"+"リードした2桁のデータ(1バイト/16進アスキーキャラクタ)"、認識されなかったら"NG"+"lf"を出力

BSをサポート。

**Comment by watari3** [comment]
上記機能の移植について質問です。

下記のどちらがよろしいでしょうか。

1) UARTは1つ。"start"+"lf"と"stop"+"lf"で重心計算の結果出力とHost I/Fを切り替える
2) UARTは2つ。

**Comment by akita11** [comment]
2.だとHW（ボード）に変更が必要なので、
1.を希望します。

**Comment by watari3** [comment]
分かりました。
1で移植を行います。

**Comment by watari3** [comment]
feature/support_host_if ブランチにてUARTによるHost I/Fを実装しました。
後ほどレジスタ表と使い方を記載いたします。

**Comment by watari3** [comment]
レジスタ表を下記として登録

doc/EyeTracker -Register Specification-.pdf

【使い方】
"stop"+"lf"→UART I/Fを重心計算出力モードからUART Host I/Fモードに切替
"start"+"lf"→UART I/FをUART Host I/Fモードから重心計算出力モードに切替
それ以外は前出の仕様参照のこと

レジスタの意味などについてはレジスタ表を参照のこと

**Comment by akita11** [comment]
pullして論理合成して動作させてみました。startとstopは動作OKです。
wrとrdの挙動がちょっと謎なところがあるので報告します。

以下、いくつかレジスタのアクセスをした結果（//以下は私が入れたコメント）ですが、書き込みがうまくいくときといかないときがあります。
まず確認ですが、wrコマンドの書式は、
(a)"wr"+<SPC>+<アドレス4桁>+<データ2桁>
(b)"wr"+<SPC>+<アドレス4桁>+<SPC>+<データ2桁>
のどちらでしょうか。
以下のログでは、(2)のところを見る限り、(a)のように理解できるのですが、同じ文字列を別のときに書き込んだときは、正しいあたいが書き込まれない(0x10を書き込んだあとでrdすると0x00のまま、など)ときがあります。（再現性がありそうでなくて、パターンをまだつめきれていない）

またこれも確認ですが、rd/wrコマンドは、start後で重心がUART出力されるときでも受け付けますか？それとも、いったんstopした後でないと受け付けない？

あともう1つ、wrコマンドでVGAOUTMODE(0x0001)を書き換えると、すぐにVGA出力がraw/digitizedで切り替わりますか？

```
wr 0002 10 // write THRESHOLD=0x10 (1)
OK

rd 0002    // read THRESHOLD=0x01?
OK
01

wr 000210  // write THRESHOLD=0x10 (2)
OK

rd 0002    // read THRESHOLD=0x10
OK
10

wr 000101  // write VGAOUTMODE=1(raw)
OK

rd 0001    // read VGAOUTMODE=0? (3)
OK
00

wr 000100  // write VGAOUTMODE=0(digitized)
OK

rd 0001    // read VGAOUTMODE=0(digitized)
OK
00

```

**Comment by watari3** [comment]
> pullして論理合成して動作させてみました。startとstopは動作OKです。
> wrとrdの挙動がちょっと謎なところがあるので報告します。
> 以下、いくつかレジスタのアクセスをした結果（//以下は私が入れたコメント）ですが、書き込みが> うまくいくときといかないときがあります。

クロック載せ替え処理に問題がありそうと思われます。
只今デバッグ中ですのでしばらくお待ち下さい。

>まず確認ですが、wrコマンドの書式は、
>(a)"wr"++<アドレス4桁>+<データ2桁>
>(b)"wr"++<アドレス4桁>++<データ2桁>
>のどちらでしょうか。
>以下のログでは、(2)のところを見る限り、(a)のように理解できるのですが、同じ文字列を別のときに>書き込んだときは、正しいあたいが書き込まれない(0x10を書き込んだあとでrdすると0x00のまま、など)ときがあります。（再現性がありそうでなくて、パターンをまだつめきれていない）

厳格に入力コマンドチェックをしていませんでしたので不思議な挙動になっておりました。
次のpush(おそらく6/15朝)で仕様どおりに動作するよう変更します。
なおコマンドについてはdesigns/sim/testbench/SIM_TOP.vの173行以降を参考ください。

>またこれも確認ですが、rd/wrコマンドは、start後で重心がUART出力されるときでも受け付けますか？それとも、いったんstopした後でないと受け付けない？

Host側が"OK" or "NG"を受信するまでをコマンドの仕様(除くstart)としているため、
基本仕様として不可ですが、内部動作としてwrコマンドは実行されます。

>あともう1つ、wrコマンドでVGAOUTMODE(0x0001)を書き換えると、すぐにVGA出力がraw/digitizedで切り替わりますか？

即時反映としているためすぐに切り替わります。
レジスタ値の反映をV Syncが来てからに変更したほうが良いですか？

**Comment by akita11** [comment]
動作仕様、理解しました。仕様自体はこれでOKです。
念のため確認ですが、PCからの送信も、7bit/parityなし/stop1bit、ですよね？

**Comment by watari3** [comment]
はい。そのとおりです。

UARTの仕様はTOP.vのUART_TX_CORE及びUART_RX_COREをインスタンシエーションしている部分を見ていただければお分かりいただけます。
なおこちらを修正することで変更も可能です。

**Comment by akita11** [comment]
いただいたものをpullしてブランチfeature/support_hostifに切り替えて試してみました。（割り算器の生成はtclでOKでした）
ただwrコマンドが、すべてNGとなるようです。
[![https://gyazo.com/17cffb30fc708eedb1465b57b4f90f0a](https://gyazo.com/17cffb30fc708eedb1465b57b4f90f0a/raw)](https://gyazo.com/17cffb30fc708eedb1465b57b4f90f0a)

**Comment by watari3** [comment]
修正しました。

**Comment by watari3** [comment]
一通りアクセスできるようになったので本件closeします。
