### ISSUE TITLE
静止画像に対してS/SX/SYがほぼ一定となること

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#19]
カメラを固定し、静止物体を撮影した状態で、S/SX/SYの値がほぼ一定（多少±10程度のバラツキは許容）となること。S/SX/SYの演算結果が正しいことの簡便な判定方法・

**Comment by watari3** [comment]
本件に関係あるかわからないが6/1 PM4:00のコードではHSIZEの検出方式に問題あり。修正版をPush済み。(実機未確認)

**Comment by watari3** [comment]
カメラからの入力信号, DVAL, FVALから入力解像度を判定する際の仕様確認

【仕様確認】
現在pushされているデザインは以下のタイミングでHSIZE(水平方向の解像度)、VSIZE(垂直方向の解像度)が更新される。

・DVALの立ち下がりタイミングでHSIZEを更新
・FVALの立ち上がりタイミングでVSIZEを更新

上記仕様ではチャタリングが発生したとき(信号が不安定なとき)、挙動が不安定になる。

a) 不安定であっても一瞬のことなので問題なし
b) 値が安定してから値の更新を行う

上記のどちらの仕様が望ましいか。

**Comment by akita11** [comment]
チャタリング、というのは、具体的にはどれぐらいバラつくのでしょうか。例えば300のところが100くらいとか大きく変わったりしますか？
いずれにしても各フレームで更新しますから、次のフレームでは戻っていますよね。であればa)がいいです。

**Comment by watari3** [comment]
デバッグをしてみました。
画面にノイズがのっているので安定していませんが以下のような結果が出力されています。
先日の静止画とはどんな条件で表示されていたのでしょうか。

0B468032BA352568FAC
0984003371A0118B45C
09AF80345CCC125126A
0AB93035649920BFAB5
09AF80345CCC125126A
0AB93035649920BFAB5
09AF80345CCC125126A
0AB93035649920BFAB5
09AF80345CCC125126A
0AB93035649920BFAB5
0C30B036EDC726690E9
09D020350D2D1264C10
0C312036EDC726690E9
09D020350D2D1264C10
0C312036EDC726690E9

**Comment by akita11** [comment]
↑でSをみると、1行目と2行目で0xb468=46184、0x9840=38976ですので、値に15%ぐらいの差があります。客観的に見てカメラも対象物も静止していて、照明も一定であれば、これほどの差は出ないはずです。
「先日の静止画」というのが何を指しているのかわからないのですが、↑のほうに目安として書いたバラツキ±10というのは、以前バージョンのものが正常に動いて眼球を観測していたときに出力されていたSの値のバラツキはこれくらいだったよなあ、という記憶のものです。ですので、これぐらいの精度は出るはずなので、正常動作の判断の目安としてあげました。

**Comment by watari3** [comment]
過去の性能(ばらつき)について理解しました。

現在値が安定しないのは画面にノイズがのっている事に起因していますのでノイズの要因を調査します。

以下ノイズの要因として考えられるものです。
何か気づく点がありましたらアドバイスいただけないでしょうか。

1) そもそもカメラから入力されるFVAL, DVAL, VVALに想定外の信号が存在している
2) (可能性はかなり低いが)Dual Port SRAMでアクセスの衝突が多発している
3) メモリアクセスに使用しているアドレスの値がおかしい

画面を見ていると1)の可能性が高いと思われます。

**Comment by watari3** [comment]
ティアリングの影響or私の家の照明の影響で画面にホワイトノイズが発生する以外問題ないことを確認済み

**Comment by akita11** [comment]
実験環境をきちんと設定して実験を行ってみました。
結論として、
(1) 静止物体に対してS/SX/SYはほぼ一定となる（動作OK）
(2) 対象物の位置を移動すると、それに応じて、Sは一定のまま、SXとSYは変化する（ほぼ動作OK：後述）
(3) S/SX/SYから求めた重心の値は、画面上の重心の位置と一致していそう（ほぼ動作OK：後述）
(4) ただ、S/SX/SYから求めた重心座標のx,yが逆っぽい。対象物を水平に移動するとSXが一定でSYが変化する。→SXとSYが出てくる順序が逆で、S/SY/SXの順でUART出力されていないか？（推測）
(5) UARTから出てくる値が、すべて0という行が、ほぼ半分ある。上記(1)-(4)は、UARTから出てくる値のうち、このすべて0という行以外のものに対して。
[![https://gyazo.com/4800947484789d45ee6f9b0465a4d0f1](https://gyazo.com/4800947484789d45ee6f9b0465a4d0f1/raw)](https://gyazo.com/4800947484789d45ee6f9b0465a4d0f1)
オシロ実測でもロジアナ実測でも、そういう行はある。（'0'=0x30で、この部分ではUART_TXDに0x30が続いている。
[![https://gyazo.com/1ad1ed57cd8153da7b6c04421dfe5f27](https://gyazo.com/1ad1ed57cd8153da7b6c04421dfe5f27/raw)](https://gyazo.com/1ad1ed57cd8153da7b6c04421dfe5f27)
なおUART波形を見る限り、データのかたまり(正しいS/SX/SYの値の行 or すべて0の行をあわせて)の周期はカメラのフレームレートの周期と一致している。

(4)はそれほど大きな問題ではない（最悪、受信側でSXとSYを逆にすればよい）のですが、(5)はちょっと問題です。つまりフレームごとの重心計算が50%ほどできていない、っぽい。別issueのSRAM書き込みの話と関連しますが、何か考えられる対策はありますか？

**Comment by watari3** [comment]
上記(5)については issue #20 の修正を行うことで解決するはず。
上記(4)については以下の修正を行うことで解決。

- TOP.v/330行目の.iSUM_SX(sum_sy)を.iSUM_SX(sum_sx)に変更
- TOP.v/331行目の.iSUM_SY(sum_sx)を.iSUM_SY(sum_sy)に変更

**Comment by watari3** [comment]
修正完了したのでclose.
