### ISSUE TITLE
重心計算処理

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#2]
重心計算処理は参考資料通りに実装する。

計算途中のデータはF/Fで保持することとする。

**Comment by watari3** [comment]
S/SX/SYの合計算出回路実装完了
除算は後ほど実装

**Comment by akita11** [comment]
1つ確認をさせてください。実機での重心計算回路の検証は、どのように行われていますか？
カメラで適当な画像を撮り、その画像を動かすと、演算結果のS, SX, SYの値も、変化する（その値が正しいかは別として）、という動作は実機で確認していますか？

**Comment by watari3** [comment]
かなり前のコードになりますが、vgaout_mode=0, threshold=0x01としてsum_s, sum_sx, sum_syが変わることをILAにて確認しております。
なお単体演算回路はシミュレーションで確認しております。

計算処理部分が少し特殊な記述で対応しているため合成時に変になる可能性は否定できません。
後ほど合成ログを確認してみます。

**Comment by akita11** [comment]
CLctrl.vをみていて気づいたのですすが、二値化の処理、以下のようになっていますよね。
`oMEMIN_0[i  ] <= (iDATA_L>iTHRESHOLD) ? 1'b1: oMEMIN_0[i  ];`
これだと、輝度がiTHRESHOLDより大きい（明るい）画素が1になって、その画素にたいして重心計算されること、になりますよね。（この理解は正しいですか？）

本来行いたいのは、THRESHOLDよりも暗い画素に対する重心計算、なのですが、そのためには、この不等号は逆、という理解でよろしいですか？（この理解が正しいのであれば私のほうで修正しておきます）

**Comment by watari3** [comment]
オリジナルのソースと思われるものが
oMEMIN_0[i ] <= (iDATA_L>iTHRESHOLD) ? 1'b1: oMEMIN_0[i ];
という記述でしたので、そのまま実装しています。

これが仕様とは正反対ということであれば修正が必要ですね。
こちらでも修正しておきます。

pushは私が行ったほうが良いでしょうか？

**Comment by akita11** [comment]
私が今日の夕方にこの修正を行ってcommitしていますので、まずはそれをpullしてください。

またvgaout_mode=0(digitize)のときに、この二値化に基づいた画像がVGA側で表示されない原因は、なにか思い当たる節はありますか？

**Comment by watari3** [comment]
issue #3 UART対応　の方に思い当たることを記載しました。
ご参照ください。

**Comment by watari3** [comment]
除算含む重心計算処理を行い、VGA出力に重心位置を赤色で出力するよう実装。

**Comment by watari3** [comment]
動作確認が取れた (issue #25 )ので本件close
