### ISSUE TITLE
raw/digitized画像のVGA表示のチラツキ

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#20]
カメラとVGAが非同期ではあるものの、ちょっとチラツキが大きいような気もする。これが正しい動作なのかは要検証。

**Comment by watari3** [comment]
WE信号の生成に起因する問題の様に思われる。
オリジナルソースを元に実装したことが原因の可能性あり。

次の合成＆配置配線をするタイミングで修正デザインを用意して確認する予定。

**Comment by watari3** [comment]
重心計算中にWEがONとなるタイミングがありデータを破壊。
重心計算中はWEを0に、またDEに同期してWEの処理行うように修正することで画面が安定することを確認済み。

**Comment by watari3** [comment]
フレームバッファの切り替え処理に問題があり重心計算がおかしくなる。

修正箇所は以下の２点

- INP_CAMERA_DATA.v/95行目のrise_vsyncをfall_vsyncに変更
- TOP.v/166行目の.iMEM_SEL(mem_sel_sync_cclk)を.iMEM_SEL(cmr_field)に変更

**Comment by watari3** [comment]
修正完了したのでclose
