### ISSUE TITLE
SRAM読出しタイミング・競合

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#21]
状況の整理を兼ねて。
・SRAMへの書き込みはカメラのクロックに同期して、カメラから
・SRAMからの読出しは、(a)VGA出力読出し(25MHz)と、(b)重心計算読出し(カメラクロック同期)の2系統
・SRAMは2バンクあり、カメラのフレームにあわせて、書き込みと(b)読出しを別バンクで交互に行う
・SRAMへのアクセスで書き込みと読出しが競合（ハザード）しうるのは、書き込みと(a)読出しだけ、のはず。ただしこの読出し時のハザードは、VGA出力のチラツキ現象として観測されるはず。この現象は重心計算には無関係のはず。
・（要確認事項）(a)読出しをどちらのバンクから行うかは、どう決めているか？→現実的には、カメラで書き込みを行っているバンク（＝(b)読出しとは別のバンク）に対して行うべき、のはず。（(a)読出しと(b)読出しは同時に行えないので）
※理想的には3ポートRAM（書き込みx1と読出しx2）があるとこれらは完全に解決できますが・・・

**Comment by watari3** [comment]
状況の整理に関して個人的見解を記載します。詳細に関しては下記備忘録の資料を読む必要があります。
（時間がなかったため先にこの文書を記載）

4) はSRAMの仕様か設定でどのような状況になるか決定するはず。（下記資料を読み解く必要あり）
5) に関しては重心計算はSP, フレームバッファはTDPを使用することで回避出来ますがBRAMの数次第

備忘録
下記資料のCollisionに関する資料を読む
https://japan.xilinx.com/support/documentation/user_guides/j_ug473_7Series_Memory_Resources.pdf

**Comment by watari3** [comment]
SRAMが不足する場合はフレームバッファとしてDRAMを使用するか。

**Comment by watari3** [comment]
競合問題を回避する方法

下記のどちらかで問題解決するのではないか。

1) SRAMのIPの設定を変更する(Port A Options & Port B OptionsのOperating ModeをNO_CHANGEからWrite Firstに変更)
2) 重心処理計算をSinglePort SRAM, Frame BufferをTrue Dual Port SRAMで実装

**Comment by akita11** [comment]
まず現状を確認させてください。↑に書いたうち以下の2点です。
(1)SRAMへのアクセスで書き込みと読出しが競合（ハザード）しうるのは、書き込みと(a)読出しだけ、のはず。ただしこの読出し時のハザードは、VGA出力のチラツキ現象として観測されるはず。この現象は重心計算には無関係のはず。
→この理解は正しいですか？

(2)（要確認事項）(a)読出しをどちらのバンクから行うかは、どう決めているか？→現実的には、カメラで書き込みを行っているバンク（＝(b)読出しとは別のバンク）に対して行うべき、のはず。（(a)読出しと(b)読出しは同時に行えないので
→現状は、(a)読み出し（VGA読み出し）をどちらのバンクから行っていますか？

**Comment by akita11** [comment]
生画像／二値画像をDRAMに格納するようにするとすると、どれぐらいの工数（改造）になりますか？
それとも、重心計算もあわせて、DRAMに入れることを考えていますか？その場合は、どれぐらいの工数になりますか？

**Comment by watari3** [comment]
(1)ですが、私が書いた設定を変更しない場合、その理解にならない場合があります。
(2)ですが、重心処理は書き込みが完了したバンクを読んでいるつもりですが、帰ってきてから確認します。違う場合はFVALの立ち上がり(VSYNCの立ち下がり)でバンク切り替えをするように変更します。

DRAMの場合はそこそこ時間がかかるはずなのでSingle Port SRAMを1つ追加のほうが工数が少ないと思っています。

**Comment by akita11** [comment]
↑で(1)で「その理解にならない」とは、具体的にはどのような現象をさしていますか？
(A)SRAMへのアクセスで書き込みと読出しが競合（ハザード）しうるのは、書き込みと(a)読出しだけ、のはず
(B)ただしこの読出し時のハザードは、VGA出力のチラツキ現象として観測されるはず。この現象は重心計算には無関係のはず。
の、どちらですか？

**Comment by akita11** [comment]
↑↑でDRAMを使う場合は工数が多そう、ということは理解しました。SinglePortSRAMを追加するリソースはありましたっけ？あ、でも、現行で、重心計算＆VGA出力用があわせてdepth=6bitなのを
・二値化フラグ格納＆重心計算用のSP(depth=1bit)
・生画像or二値化フラグ格納＆VGA出力用のTDP(depth=現行5bitだがこれより少なくてもOK)
に分けるだけなので、BlockRAMリソースとしては、それほど変わらない（＝大きな変更はないので工数が少ない）、という理解であってますか？

**Comment by watari3** [comment]
少し異なりますので補足いたします。

> (A)SRAMへのアクセスで書き込みと読出しが競合（ハザード）しうるのは、書き込みと(a)読出しだけ、のはず
> (B)ただしこの読出し時のハザードは、VGA出力のチラツキ現象として観測されるはず。この現象は重心計算には無関係のはず。

まず説明する前にカメラ側のクロックをCCLK、ビデオ出力側のクロックをVCLKと定義します。
(A)についてはCCLKによるWriteとVCLKによるReadになります。ここでどのデータを優先するかについて明示しないと競合が発生した際にWrite側が破壊されるか、Read側が破壊されるかわかりません。

このようなことがありますので明示的に設定していないと、(B)として記載されているVGA出力のチラツキ現象として観測されるはず、とならない場合があります。

また確率が極めて低いとは思いますが、VCLK側のReadの始まりor終わりとCCLK側のReadの始まりor終わりのタイミングでアドレスまたはEnableまたはWrite信号のsetup/holdエラーが発生した場合SRAMの内容の破壊の可能性があるはずです。
こちらについてはめったに発生しないはずなので本件と関わりはなさそうだと思いますが発生する可能性はあります。

**Comment by akita11** [comment]
なるほど。理解しました。ということは、SRAMのIPの設定を、WriteFirstにして試してみる、のがいいですかね。

**Comment by watari3** [comment]
DRAMまたはSinglePortSRAMでの対応について記載します。

> ↑↑でDRAMを使う場合は工数が多そう、ということは理解しました。SinglePortSRAMを追加するリソースはありましたっけ？あ、でも、現行で、重心計算＆VGA出力用があわせてdepth=6bitなのを
>・二値化フラグ格納＆重心計算用のSP(depth=1bit)
>・生画像or二値化フラグ格納＆VGA出力用のTDP(depth=現行5bitだがこれより少なくてもOK)
に分けるだけなので、BlockRAMリソースとしては、それほど変わらない（＝大きな変更はないので工数が少ない）、という理解であってますか？

そもそもオリジナルデザイン、つまりILAなしの状態、であれば60%程度以下のSRAMしか使っていないはずです。
よってILAの設定を変えることで1bit程度であればSRAMを捻出できます。
また、上記に記載されている＆ご認識の通り現行のVGA出力用のTDPのうち1bitを重心計算専用に割り当てるでも構いません。

なおどちらもRTLを記述する、という工数では誤差の範囲内ですし、ILAの調整が必要だったとしても半日以下の工数(最短1時間程度)で実現できると思われます。

またご理解されているようにDRAMの場合以下のような回路を実装しないとならず、多少時間がかかります。

・MIG(DRAMのPhisical PHYと初期化シーケンスロジック)の実装
・DFI(DRAM PHYとユーザー回路を繋ぐInterfaceの仕様)に合わせた信号生成回路の実装
・Line Memory or FIFO Bufferの実装
・DRAMアドレス生成回路の実装
・ピン配置確認及びXDCの準備

**Comment by watari3** [comment]
>なるほど。理解しました。ということは、SRAMのIPの設定を、WriteFirstにして試してみる、のがいいですかね。

別でも記載しますが、4箇所の修正でほぼ安定するようになりますが、上記修正をしていないと、たまに誤動作している、となると思われます。

という訳ですのでWriteFirst修正をお願い致します。

**Comment by akita11** [comment]
関連して1つ確認をさせてください。（質問したつもりでしたが見当たらないのでしていなかったようです）
SRAMからの読出しを行うのが、VGA読出しと重心計算読出しの2つがありますが、この両者が競合することはありえますか？
（私の理解では、SRAMが2バンクあって、VGA読出しはカメラ書き込み側バンク、重心計算読出しはその逆側バンクなので、VGA読出しと重心計算読出しは競合することはありえない、と理解していますが、これで正しいですか？）

**Comment by akita11** [comment]
とりあえずメールでいただいた4点の修正＋WriteFirstに変更して、動作ためしてみます。

**Comment by watari3** [comment]
> SRAMからの読出しを行うのが、VGA読出しと重心計算読出しの2つがありますが、この両者が競合することはありえますか？

そこそこの確率で発生するはずです。

以下理由。

重心計算はFVALの立ち下がりをトリガーに計算を開始し、Y方向のサイズ[cycle]かけてSRAMにアクセス。このSRAMアクセスではアドレスが0からY方向のサイズ-1まで変化する。

カメラ側のフレーム周期とVGA側のフレーム周期が異なるかつカメラ側のフレーム周期が早いため、この２つのフレーム周期の最小公倍数時間後、逆バンクアクセスが成り立たなくなり、そのカメラ側の1フレーム分の１周期のFVALの立ち下がりからしばらく経過したところでアクセスの衝突(競合)が発生します。

これはほぼ同じ周期であっても２つの最小公倍数時間後に衝突(競合)が発生するので、回避するには入力のフレームと出力のフレームを揃える必要があります。(*1)

しかしながらカメラのフレームレートをVGAのフレームレートよりかなり大きくしているため回避出来ません。(*2)

*1)
フレーム同期処理(GENLOCK制御のような処理)を行い、VGAの出力フレームに揺らぎを与えることで競合を回避できますが(*2)の条件があるためフレーム同期不可となるはずです。

**Comment by akita11** [comment]
なるほど、（だいたい）理解しました。これはまずいな・・・
ちなみに逆バンクアドレスが成立しない状態での、SRAMの読み出しアドレスは、実際にはどちらになりますか？VGA出力側と重心計算側の両方からアクセスをしようとしても、実際にSRAMに与えられるアドレスは、どちらかですよね。

VGA出力のほうが優先度が低い（確認用なので）ことを考慮すると、
VGA出力と重心計算が、同一バンクに同時にアクセスをしようとした場合は、重心計算のほうを優先させる（VGA出力側の読み出しを無視する）ことができれば、この問題は解消できると思うのですが・・・

**Comment by akita11** [comment]
昨日あげられた修正点（4点＋WriteFirst）を行って動作させて見ました。SX/SYの入れ替わりは（当然ながら）解消されましたが、すべて'0"の行が（ほぼ）交互に出てくる現象は変わりませんでした。これの原因として、考えられることはありますか？
[![https://gyazo.com/b9c6ac7b1c0c8d6f495ae896ce367d06](https://gyazo.com/b9c6ac7b1c0c8d6f495ae896ce367d06/raw)](https://gyazo.com/b9c6ac7b1c0c8d6f495ae896ce367d06)
あともう1つ、これとは無関係そうな現象をみつけたので、別issueたてます。

**Comment by watari3** [comment]
>ちなみに逆バンクアドレスが成立しない状態での、SRAMの読み出しアドレスは、実際にはどちらになりますか？VGA出力側と重心計算側の両方からアクセスをしようとしても、実際にSRAMに与えられるアドレスは、どちらかですよね。

これは運任せになるはずです。

厳密に言うと一瞬でも先にアクセスしたほうが優先。
後の方は最悪setup or holdエラーが発生して値が不定になります。
デバイス固有であり、また(P)VTにも左右されるので最初に書きましたように運任せになります。

>VGA出力のほうが優先度が低い（確認用なので）ことを考慮すると、
>VGA出力と重心計算が、同一バンクに同時にアクセスをしようとした場合は、重心計算のほうを優先させる（VGA出力側の読み出しを無視する）ことができれば、この問題は解消できると思うのですが・・・

TOP層にあるgrav_sel_enをVGA側からのSRAMアクセス禁止信号に利用すれば可能です。

完璧を求めるのであれば下記のどちらかで対策できそうです。
Plan 2)の実装が簡単ですが、時々(or稀に)アクセスエラーが発生するはずです。
Plan 1)ではCCLKクロックでVSIZE+α[cycle]アクセス禁止が発生しますので、その間VCLKクロックで0が出力されます。

どちらを用意いたしましょうか。

Plan 1)
・重心処理ステートマシーンにSRAMアクセス禁止信号を出力するステートを2つ追加（クロック周波数の違い、メタステ対策を考慮した回路とすること）
・VGA側に上記信号をメタステ対策して受け取る回路を追加
・上記VGA側クロックに同期した信号を用いてSRAMのアクセスを停止(CSを落とす)

Plan 2)
・CCLKクロック同期のアドレス信号をメタステ対策してVCLKクロックで受信(バスを持っている信号なので正確に信号を受信することは難しい)
・VCLKクロックでアドレスの衝突検出回路を動作

**Comment by watari3** [comment]
>昨日あげられた修正点（4点＋WriteFirst）を行って動作させて見ました。SX/SYの入れ替わりは（当然ながら）解消されましたが、すべて'0"の行が（ほぼ）交互に出てくる現象は変わりませんでした。これの原因として、考えられることはありますか？

UARTから0が出力される件の詳細解析を行う必要があるのであればTOP層の下記信号とUARTの相関を取得していただけないでしょうか。

- cmr_field (CCLKクロック同期でSRAMアクセスバンクを決定)
- cmr_vsync (この立ち上がりをトリガーに重心処理を開始。CCLKクロック同期)
- mem_sel (VCLKクロック同期でVGA側のSRAMアクセスバンクを決定)
- grav_sel_en (CCLKクロック同期で、これがHighの間重心計算を実行)
- start_trig (CCLKクロック同期。UARTのbpsの8倍のクロックで受信できる信号を出力。UART IFの出力開始信号として使用)

これらの関係からおおよそ何が原因か見えてくるはずです。

なお本件は、重心計算用にSP SRAMを用意する事で回避できます。

**Comment by watari3** [comment]
衝突の発生頻度を下げる方法として、本当に必要なアクセス時以外CSを落とす(CCLK/VCLKどちらとも)、という対策案がありますが準備したほうがよろしいでしょうか。

なお現行デザインではオリジナルデザインと同様にフレームの切り替わりでCSを変更しています。
(必ずどちらかのSRAMのCSが有効になる)

ご意見を伺いたく。
ご回答願います。

**Comment by akita11** [comment]
上記Plan1で、VCLKがとまる、とのことですが、HSYNC/VSYNCは影響を受けますか？影響を受けないのであれば、画面表示の同期信号は現行通りで、ところどころの画素がズレる、ということになりますよね。アクセスできなかった画素に対しては、skipするようにできれば、例えば1234の順の画素値が1224、のように(3のところがアクセスできなかった)なって、VGA表示上はそれほど影響がない、と思えます。この方法が一番よさそうに思えますが、どんなもんでしょう。

**Comment by akita11** [comment]
改めていただいた情報を理解しました。
SRAMを重心計算用とVGA出力用を分けるのが、
結果として早くて確実、な気がしてきました。
この方針での修正をお願いしてよろしいですか。
VGA出力用の方のdepthは、リソースの許す限り、でいいです。
また重心計算用と分けるので、ニ値化時と生画像出力時のメモリは分けず、
カメラからの書き込み時に、ニ値化するか生画像か、をvgaout_modeで切り替えればいいですよね。

>

**Comment by watari3** [comment]
>上記Plan1で、VCLKがとまる、とのことですが、HSYNC/VSYNCは影響を受けますか？影響を受けないのであれば、画面表示の同期信号は現行通りで、ところどころの画素がズレる、ということになりますよね。アクセスできなかった画素に対しては、skipするようにできれば、例えば1234の順の画素値が1224、のように(3のところがアクセスできなかった)なって、VGA表示上はそれほど影響がない、と思えます。この方法が一番よさそうに思えますが、どんなもんでしょう。

Plan 1)のVCLKが止まるとは、CCLKクロックでVSIZE時間/VCLKのクロック周期+α　時間SRAMアクセスが止まることを指しています。
この時間の間

a) 前のデータを保持する
b) 0を出力する

のどちらかを実装することで見え方が変わります。
なおVGAのタイミング生成回路とSRAMアクセスは独立していますのでHSYNC/VSYNCが止まるorおかしくなることはありません。

**Comment by watari3** [comment]
>SRAMを重心計算用とVGA出力用を分けるのが、結果として早くて確実、な気がしてきました。
>この方針での修正をお願いしてよろしいですか。
>VGA出力用の方のdepthは、リソースの許す限り、でいいです。
>また重心計算用と分けるので、ニ値化時と生画像出力時のメモリは分けず、
>カメラからの書き込み時に、ニ値化するか生画像か、をvgaout_modeで切り替えればいいですよね。

上記の件承知しました。

以下備忘録

- 重心計算用のSRAMはSP SRAMとして別途用意する(これを行わないとRead同士の衝突は回避できない)
- CLctrl内でvgaout_mode信号を見て何を書き込むか(2値化データ or Rawデータ)を決定する
- VGA側はSRAMのデータを何も考えずに出力する

**Comment by akita11** [comment]
はい、お願いします。あと確認ですが、これを行っていただくならば、例のUARTから'0'や異常に小さな値が出てくる原因をみるために内部信号を観測する、のは、いまは行わなくてもよいですよね。

**Comment by watari3** [comment]
RTL変更前にTOP.v 214行目に不具合の原因となりうる記述を見つけました。
この修正したものをpushしておきます。(先日ご連絡した4箇所の修正 + 本修正を実施したもの)
RELEASE_CANDIDATE_1 tagのデザインを用いてご確認をお願い致します。

**Comment by akita11** [comment]
こちらは、SRAMをVGA出力用と重心計算用で分離したものですか？
もしそうでなければ、競合が起こりうる回路での動作チェックはあまり意味がないと考えますが、それでも動作チェックを行った方がいいですか？

**Comment by watari3** [comment]
>以下備忘録
>
> -重心計算用のSRAMはSP SRAMとして別途用意する(これを行わないとRead同士の衝突は回避できない)
> -CLctrl内でvgaout_mode信号を見て何を書き込むか(2値化データ or Rawデータ)を決定する
> -VGA側はSRAMのデータを何も考えずに出力する

上記の仕様確認。
そもそも重力計算用のSRAMを別途用意する場合、ダブルバッファ用のSRAMは不要ではないでしょうか。

もし不要であれば、現状のILAを実装(BRAM使用率約30%)したとしても、色深度8bitでVGA出力かつ重力計算用SRAMも実装可能です。

本件について回答いただければ幸いです。

**Comment by akita11** [comment]
いえ、現行の方法では、重心計算用のRAMは2バンク必要なはずです。
重心計算を、FVALがおわったところからY方向の累算を開始し、その後X方向に累算しますよね。これが480(Y)+640(X)=1120クロック。
これがVブランクの期間中に終わるのであれば、ご指摘のように2バンクは不要で、1バンクでOKです。このVブランク期間中に終わりますか？

終わらないのであれば、書き込み用と読出し用が別なので、2バンク構成必要です。

理想論を言うと、1行分の読み込みを行いながらY方向累算は1行ごとに実行できますので、
FVALが終わった時点で、Y方向の累算を終えることはできます。
残りのX方向累算をVブランク期間中に行う、という方法も、一応可能です。（アルゴリズム1)

さらに理想論いうと、カメラから画素ごとに値が送られてくるわけですから、
画素ごとに、S/SX/SYを累算して求めていき、FVALが終わった時点で、S/SX/SYの演算が終わっている、ということも、一応可能です。（アルゴリズム2）

ただこれらのアルゴリズム1とアルゴリズム2は、仕込みを始める前にご相談して、これらの方法も可能ですが、お任せします、とお伝えしていましたが、オリジナルのアルゴリズム（読出し後にY累算→X累算の順）に沿って実装します、と言われて、その通り実装していただいている、という経緯です。





2017年6月6日(火) 21:55 watari3 <notifications@github.com>:

**Comment by watari3** [comment]
>重心計算を、FVALがおわったところからY方向の累算を開始し、その後X方向に累算しますよね。これが480(Y)+640(X)=1120クロック。
>これがVブランクの期間中に終わるのであれば、ご指摘のように2バンクは不要で、1バンクでOKです。このVブランク期間中に終わりますか？

カメラの最小Vブランク期間がわからないのでなんとも言えませんが、1120クロック=2H未満となり、一般的なビデオ信号(notカメラ信号)であれば計算は完了します。

今回はVGA出力用のSRAMを2つ削除(1bit分)し、重心計算用に2つ(ダブルバッファ)追加しています。
(現在implement中)
コードは最小限の修正としたく、前出の備忘録通りに修正はしていませんが機能等価となるよう修正しています。

**Comment by watari3** [comment]
>こちらは、SRAMをVGA出力用と重心計算用で分離したものですか？
>もしそうでなければ、競合が起こりうる回路での動作チェックはあまり意味がないと考えますが、それでも動作チェックを行った方がいいですか？

下記の手順でご確認いただければ幸いです。

1) 6時代に重心計算用にSRAMを割り当てたデザインをpushします。まずはこちらで確認願います。
2) 1)の結果がNGの場合6/6に記載した信号をILAで確認願います。結果から不具合箇所を調査します。
3) お時間があるようでしたらRELEASE_CANDIDATE_1 tagのデザインで確認をお願い致します。(1)のRTL修正に根本的な間違いがあった場合)

**Comment by akita11** [comment]
わかりました、その手順でやってみます。
1.2.の「6時台」のcommitがあるブランチは、calculate_center_of_gravity、でいいですか？

**Comment by watari3** [comment]
そうです。feature/calculate_center_of_gravityブランチの最新を利用ください。

なお基本修正ファイル1つ毎にコメントを記載し、何箇所かの修正をまとめてpushしています。

**Comment by akita11** [comment]
↑をimplementして動作させてみました。
・以前のように、対象物が右端付近にあるときに、「すべて'0'ではなくて異常に小さな値」にならず、「すべて'0'」が出るようになった（対象物が左端や中央にいるときも同様）
・以前は、「すべて'0'」が、2～3回に1回だったのが、見ている限りは、ちょうど2回に1回（正常値と交互）に出るようになった。
まずは↑の2.の手順へ進めてみます。
[![https://gyazo.com/3b59aa12583c11966265f4bc86388c91](https://gyazo.com/3b59aa12583c11966265f4bc86388c91/raw)](https://gyazo.com/3b59aa12583c11966265f4bc86388c91)

**Comment by akita11** [comment]
2.へ進んで、指定された信号をILAでみてみました。この部分を拡大してほしい、などがあればご指示ください。
[![https://gyazo.com/7659b80190d1f9c755a91126ff01a1d1](https://gyazo.com/7659b80190d1f9c755a91126ff01a1d1/raw)](https://gyazo.com/7659b80190d1f9c755a91126ff01a1d1)

**Comment by akita11** [comment]
もう1個とってみました。横軸8000-28000あたりで「すべて'0'」の行、59000あたりから正常値と思われる値がUARTから出てきています。
[![https://gyazo.com/a10776516abc25ef276533d599ba5fad](https://gyazo.com/a10776516abc25ef276533d599ba5fad/raw)](https://gyazo.com/a10776516abc25ef276533d599ba5fad)

**Comment by watari3** [comment]
Typoを見つけ修正しました。
これで直るはずです。

もしこれでも直らない場合は以下の信号を追加してILAで測定してもらえないでしょうか。

・(TOP層にある)cmr_wea
・(TOP層にある)cmr_web

**Comment by akita11** [comment]
ありがとうございます、これから試してまたご報告します

秋田
2017年6月8日(木) 6:45 watari3 <notifications@github.com>:

**Comment by akita11** [comment]
実機動作確認しました。「すべて'0'の行」は現れなくなり、また対象物が右端のほうにあるときに異常にS/SX/SYが小さくなる現象も起こりませんでした。
得られたS/SX/SYから求めた重心の値は、対象物が静止している状態ではほぼ一定（±2程度）でした。
以上から、動作はOKそうです！

2017-06-08 7:28 GMT+09:00 Junichi Akita <akita@is.t.kanazawa-u.ac.jp>:

**Comment by watari3** [comment]
では今晩になりますがfeature/cacl_gravity_of_centerブランチをmasterブランチにマージしfeature/cacl_gravity_of_centerブランチ及び関連するissue(issue #1 , issue #19 , issue #20 , issue #21 , issue #22 )をクローズすることにします。

この作業の後、tclによる環境構築(issue #8 ), MMCM IPの生成不具合(issue #17 ), Host IFの実装(issue #3)を取り組む予定です。

**Comment by akita11** [comment]
はい、よろしくお願いします。個人的にはissue#3 が優先度高めだとありがたいです。残りの2つは、プロジェクト一式を移行した今となっては、現時点では問題になっていないので。。。

**Comment by watari3** [comment]
修正完了したのでclose
