### ISSUE TITLE
右端のほうでの重心計算処理

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#22]
撮影領域の左のほうや中央付近に対象物があるときは、正しい重心の値が求められているようになりましたが、右端付近にあるときに、S/SX/SYの値が、ときどき異常に小さくなる現象があります。
例えば以下のような二値化後の画像（カメラの撮影領域のほぼ右端に円がある）のときです。
[![https://gyazo.com/66d080844fe506eeb5093d82ce1b8689](https://gyazo.com/66d080844fe506eeb5093d82ce1b8689/raw)](https://gyazo.com/66d080844fe506eeb5093d82ce1b8689)
このときの正しいと思われるS/SX/SYの値は、16進表記でそれぞれ、01000、0260000、007000付近です（得られるS/SX/SYの値から求めた重心や、同じ対象物を左に水平に移動させて画面中央付近にあるS/SYの値から推定）
これらの正しい値が求められるフレームもあるのですが、交互かそれよりやや低い頻度で、それぞれ00150、001700、0008000付近の値が出てくるようです。
[![https://gyazo.com/f730f5d3f75a081f7060ed7e452a88e8](https://gyazo.com/f730f5d3f75a081f7060ed7e452a88e8/raw)](https://gyazo.com/f730f5d3f75a081f7060ed7e452a88e8)

ただこれは、別issueで報告していた、「すべて'0'の行が半分くらい交互に出てくる」現象と似ていて、
・対象物が中央付近にあるとき→すべて'0'の行が半分くらい
・対象物が右端にあるとき→00150、001700、0008000付近の行が半分くらい（異常に小さな値）
となる、とみることができます。

つまり、約半分くらいのフレームで、S/SX/SYが、「すべて'0'」または「異常に小さな値」となる、とみることができるわけですが、これの原因はわかりますか？
別issueの、SRAMアクセスのVGA読み出しと重心計算読み出しの競合、が原因のように思えます。

**Comment by watari3** [comment]
なんとも言えませんが issue #21 と関係していそうです。
issue #21 でお願いした信号を測定していただけないでしょうか。

取り敢えず今晩何らかの対策でSRAMを捻出したSP SRAM追加版のデザインをpushします。
これまでの修正も一通りしてこちらからpushします。

【お願い事】
issueを記載される場合「別issue」という言葉を使うのではなく「issue #番号」で記載いただけないでしょうか。
githubの機能にて関連付けが行われ、振り返りの際に見やすくなります。

**Comment by akita11** [comment]
わかりました、明日の朝イチで実機での確認・測定をしてみます。またご報告します。
（あとissue番号の件は失礼しました、了解です）

**Comment by akita11** [comment]
解決したのでcloseします。
