### ISSUE TITLE
除算による重心計算

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#23]
除算による重心計算の仕様確認になります。
以下の仕様で進める予定ですがよろしいでしょうか。
また色は何色にしましょうか。(オリジナル　黒、提案　赤 or 設定で変更可能)

【仕様】
- FVALの立ち下がりをトリガーに計算された∑S, ∑Sx, ∑Syより重心を計算する
- 重心は内部レジスタで保持されマーカーとして○○色で出力
- 計算結果はHost I/Fから確認可能

**Comment by akita11** [comment]
仕様の最初の2つは齟齬ありません。（色は・・・赤（で、れきれば十字マークがいいですね）計算結果の重心値のUARTからの出力フォーマットは別途（都合のいいように）定義してください（現実的には固定小数点ですよね）。また可能であれば、現行のS/SX/SY出力と、それから求めた重心値の出力、をコマンドで切り替えられるとベストですが、これはオプションとして。

仕様の3つ目の「計算結果はHosftI/Fから確認可能」の意味がわからないので、教えてください。

あと、各種設定のコマンドですが、面倒であればもっと短く1文字＋LF（例えば開始はS+LF、停止はs+LF、など）でもいいです（提案のままでもいいです：実装が楽なほうで）。

**Comment by watari3** [comment]
「計算結果はHosftI/Fから確認可能」とは「計算結果をF/Fに保持しており、その値をHost I/Fを介して外部から値を読み出すことが可能」という事になります。

**Comment by akita11** [comment]
理解しました。その機能はあるとうれしいです（が優先度は低めで結構です）。

**Comment by watari3** [comment]
レジスタ表をアップデートしました。Host I/F側から各種値を確認することが可能です。

またDIV_28_20のIPを更新しましたので一度プロジェクトからファイル含め削除し再度tclを実行願います。

**Comment by akita11** [comment]
実機動作させてみました。レジスタ0x01(VGAMODE)にwrして、raw/digitizedの切り替え（VGA出力で）はOKでした。
ただレジスタ0x02(THRESHOLD)を読み出すと常に0xffのようです。（以下では0x10を書き込んで、その後読み出したところ。0xffが読み出されている）ただVGAMODEをdigitized設定すると、そのwrしたTHRESHOLDに応じた二値化が行われているようです。(THRESHOLDを変えると二値画像も変わる）
また他のレジスタも、rdで読み出したところ、すべて読み出し値が0xffとなるようです。
書き込みはOKで、読み出しがNG、ということでしょうか。
[![https://gyazo.com/31ce07619052ec673b372c3c091e8454](https://gyazo.com/31ce07619052ec673b372c3c091e8454/raw)](https://gyazo.com/31ce07619052ec673b372c3c091e8454)

ところでstart後にS/SX/SYが出力されていますが、これをQX/QY（割り算後の重心）に変更することは、けっこう手間ですか？（せっかく重心演算をFPGA側で行っているなら、それをUART出力するといいかな、と思ったのでした）

**Comment by watari3** [comment]
>ただレジスタ0x02(THRESHOLD)を読み出すと常に0xffのようです。

すみません。レジスタを追加したところのcase文中のdefault文が抜けていたためsynthesis&implement後おかしくなっていました。
修正対応いたしました。

>ところでstart後にS/SX/SYが出力されていますが、これをQX/QY（割り算後の重心）に変更することは、けっこう手間ですか？（せっかく重心演算をFPGA側で行っているなら、それをUART出力するといいかな、と思ったのでした）

デバッグしきれていませんが仮対応したものをpushしました。
レジスタ表のOUT_SELを変更して確認いただければ幸いです。

**Comment by watari3** [comment]
トリガー信号の幅問題を修正しました。(異なるクロックドメイン)

**Comment by watari3** [comment]
issue #25 より

>1点だけ確認をさせてください。OUT_SEL=1としてS/QX/QYをUART出力しているときのそれぞれのビット数は、OUT_SEL=0でS/SX/SYのときと同じでしょうか。とすると、QX/QYは整数部分のみの出力、でしょうか。（ちなみにですが、これを小数部を含む書式に変更することは、けっこう手間でしょうか？）

ご認識の通りQX, QYは整数部のみ出力しています。
現在除算回路は商と余りを算出するようになっています。
小数部を含む形への変更は容易ですが、仕様を確認させてください。

- 除算結果を商と余りを算出する→小数部を含む商を算出するに変更
- 出力結果はどのように出力するか？現行のアスキー文字を出力するを保持 or バイナリー出力(その場合はUARTを7bitから8bit出力に変更します。)
- アスキー出力の場合どのようなフォーマットで出力するか？
- 結果出力にどのくらいの時間をかけてもよいか

以上、ご回答の程よろしくお願いいたします。

**Comment by akita11** [comment]
>
>
>    - 除算結果を商と余りを算出する→小数部を含む商を算出するに変更
>
> はい、それが理想です


>
>    - 出力結果はどのように出力するか？現行のアスキー文字を出力するを保持 or バイナリー出力(
>    その場合はUARTを7bitから8bit出力に変更します。)
>    - アスキー出力の場合どのようなフォーマットで出力するか？
>
> 固定小数点のアスキー出力、が理想です。
例えば現行でSXの部分は28bit(7桁)ですよね。
QXは最大で640なので整数部は10bit。キリがわるいので、
整数部=12bit（3桁）、小数部16bit（4桁）
の固定小数点、はいかがでしょう。

>
>    - 結果出力にどのくらいの時間をかけてもよいか
>
>  次のフレームが始まる前には出力を終えたいところですが、間に合いますか？

**Comment by watari3** [comment]
>QXは最大で640なので整数部は10bit。キリがわるいので、
>整数部=12bit（3桁）、小数部16bit（4桁）
>の固定小数点、はいかがでしょう。

除算IPの仕様上小数部は20bitとなりますが、上位16bitのみ使用で問題ないでしょうか。

**Comment by akita11** [comment]
>
> 除算IPの仕様上小数部は20bitとなりますが、上位16bitのみ使用で問題ないでしょうか。
>
はい、もちろんそれでOKです。

**Comment by watari3** [comment]
実装完了しpush済み。DIVのIPは再生成する必要あり。
レジスタ表をUpdateし小数部もレジスタアクセスにて確認可能。

**Comment by watari3** [comment]
1つ質問ですが除算で0による除算を行った場合何かしらの情報を出力する必要はありますか？
現状だと商がFFF、小数部が不定(値未定)になります。

**Comment by akita11** [comment]
その仕様のままでokです

**Comment by watari3** [comment]
失礼しました。pushが一部抜けていました。
こちらでご確認ください。

**Comment by akita11** [comment]
確認しました、S/QX/QY出力OKですので、本件closeします。
