### ISSUE TITLE
画面が少しずれる？

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#24]
TMG_CTRL.vのhcount, vcountの意味を取り違えてVGAout.vで利用しているためX方向で画面のズレが生じる記述になっている。

TMG_CTRL.vのhcount, vcountとは別にdeでカウントアップする位置情報を表す回路を追加し、配線をそれに変更すること。

**Comment by watari3** [comment]
修正しcommit&push済み

**Comment by akita11** [comment]
いま論理合成かけていますので動作させてから報告します。

**Comment by akita11** [comment]
こちらを使って動作させてみました。
・rdコマンドでレジスタ値を読むのは正常そう（書き込んだ値と同じものが読み出される）
・CURSOR_MODEのCURMD=1としても、画面上ではカーソルを確認できない（確認ですがカーソルONのときは、VGA出力モードがdigitized/rawのいずれでも表示されますか？digitizedのときのみ？あと、カーソルの形状は赤十字？赤点？）
・CURSOR_MODEのOUT_SELを1とすると、start後にUARTからこんな感じのデータが出てくる。ところどころ0-9/A-F以外の文字が出ている。
[![https://gyazo.com/559096b500c2b55737747ad321ef6903](https://gyazo.com/559096b500c2b55737747ad321ef6903/raw)](https://gyazo.com/559096b500c2b55737747ad321ef6903)
・OUT_SEL=0としてstartしたときも、ところどころに同様の文字がはいる（いずれも各行の最初の4-5文字だけっぽい）
[![https://gyazo.com/ef6f0d6da461d04e1a4f88396875846e](https://gyazo.com/ef6f0d6da461d04e1a4f88396875846e/raw)](https://gyazo.com/ef6f0d6da461d04e1a4f88396875846e)

**Comment by watari3** [comment]
お時間ありましたらTOP.vのsum_s, sum_sx,sum_sy, quotient_sx, quotient_syの値を観測していただけないでしょうか。
できれはUART信号と同期してもらえると助かります。(UART_Tx回路へ8bitのデータ)

**Comment by akita11** [comment]
とりあえずILAの構成を8bitごとに観測するように変更して、リソースがゆるすだけ観測してみます。また報告します。
なお再度の念のための報告ですが、S/SX/SYの値そのものは正常そう（＝PCでこれらの値から求めた重心座標は、実際にカメラに映っている対象物の重心と一致している）です。

**Comment by akita11** [comment]
いくつかとってみました。他に観測すべき信号があればご指示ください。（UARTの出力トリガーをみて、それをトリガーとして観測した方がいいのかな・・・）
[![https://gyazo.com/231e191139d0b8906dc4a849f232309e](https://gyazo.com/231e191139d0b8906dc4a849f232309e/raw)](https://gyazo.com/231e191139d0b8906dc4a849f232309e)

[![https://gyazo.com/8420ba248ba0462f8a993bb11f96728c](https://gyazo.com/8420ba248ba0462f8a993bb11f96728c/raw)](https://gyazo.com/8420ba248ba0462f8a993bb11f96728c)

**Comment by watari3** [comment]
>・rdコマンドでレジスタ値を読むのは正常そう（書き込んだ値と同じものが読み出される）

Host I/Fについては完成したと判断し関連issueをcloseしました。

>・CURSOR_MODEのCURMD=1としても、画面上ではカーソルを確認できない（確認ですがカーソルONのときは、VGA出力モードがdigitized/rawのいずれでも表示されますか？digitizedのときのみ？あと、カーソルの形状は赤十字？赤点？）

現状digitized時のみ表示される仕様です。
カーソルの形状は小さい赤十字でしたが見えにくいので赤十字に変更しました。

>・CURSOR_MODEのOUT_SELを1とすると、start後にUARTからこんな感じのデータが出てくる。ところどころ0-9/A-F以外の文字が出ている。

該当回路間でメタステ対策が必要とは思っていないのですが、下記結果よりメタステが発生していると判断し対策を入れました。

修正版のRTLは6/21 AM7:00頃までにpushします。

**Comment by watari3** [comment]
動作確認が取れた(issue #25 )ので本件close
