### ISSUE TITLE
重心計算結果のVGA出力上の表示

### ISSUE THREAD

**Issue by akita11** [akita11/EyeTracker#25]
求めた重心位置を、VGA出力上に赤の十字で表示する（この機能は未実装？）

**Comment by watari3** [comment]
サポートしているつもりですが、CURSOR_ENの設定を変えても変化ないですか？

このあたりテストベンチでは確認しづらく実機の写真を送付いただければ幸いです。

**Comment by akita11** [comment]
失礼しました、CURSOR_ENというレジスタで、表示ON/OFFを切り替えられるのですね。
これをONにしたところ、モニタ上に赤マークは表示されるのですが、ちょっと位置がずれています。
https://www.dropbox.com/s/tav4p8dlwoxjheh/2017-06-20%2007.37.15.jpg?dl=0
（この写真の付近中央付近の赤丸内）
対象物（円図形）を動かすと、それに応じて（同じ向きに）赤マークも動くのですが、動き幅が小さいように思えます。感覚的には、赤マークの移動量が対象物の移動量の半分程度、でしょうか。（ということは重心の座標が実際の1/2になっている？）

**Comment by watari3** [comment]
すみません。写真見ても赤のマーク見つけれませんでした。
（小さすぎて見えない？）
もしよろしければ6/20 AM 7:00頃のデザインでOUT_SELという設定を変更することでUART上に∑S, ∑SX,∑SY出力と∑S, QSX=(∑SX/∑S), QSY=(∑SY/∑S)の切り替えが出来ますのでこれで確認していただけないでしょうか。

**Comment by watari3** [comment]
また位置がずれている件、issue #24 と関連しているようにも思っています。
issue #24 に対してコメントいただけないでしょうか。（以前のものと最近のものとで差があるか、など）

**Comment by akita11** [comment]
赤マークの写真、こちらです。
[![https://gyazo.com/dd4b05ad9ca488b60d3cf816d0e83064](https://gyazo.com/dd4b05ad9ca488b60d3cf816d0e83064/raw)](https://gyazo.com/dd4b05ad9ca488b60d3cf816d0e83064)

なおstart後にUARTから出力されるS/SX/SYからPC側で求めた重心座標は、正しい位置のようにみえます。
issue #24 は、いま論理合成かけています、動作させた結果は追々。

**Comment by watari3** [comment]
デバッグ用に6/20夜にVGA出力側にテストパターン生成回路を実装します。
これを用いて実機でバッグできる体制を作ります。

**Comment by watari3** [comment]
この件原因判明しました。
修正版を6/21AM7:00までにpushする予定です。

**Comment by akita11** [comment]
issue #23 、issue #24 とも関連するのですが、動作結果の報告です。
簡単にまとめると、
・重心計算（割り算）はOKそう
・VGA出力上に表示されるマーカの形状がおかしい（位置はOKそう）
・ところどころS/SX/SY出力値がおかしい

以下、詳細です。

まず動作させると、↓のような赤線が現れます。縦線が2本、うち1本は重心のX座標と一致しているっぽい。
https://www.dropbox.com/s/0spxvsmxdevlwv3/2017-06-21%2008.35.35.jpg?dl=0

その後、wrでCURMD=1（重心カーソルON）とすると、↓のような黒い小さい正方形(2x2画素程度)が現れます。この位置は対象物の重心に一致していると思われ、対象物を移動させると、それに追随してこの小さい正方形も重心位置で移動します。
https://www.dropbox.com/s/xzrr9uug2moa5xa/2017-06-21%2008.34.32.jpg?dl=0

以上から、割り算での重心計算はOKそうに思えるのですが、その位置の表示方法がおかしいのではないかと推測されます（赤線の形状がおかしい、黒い正方形は何か？）

またS/SX/SY出力をみてみると、ところどころ（感覚的には10行に1回くらい、ただし間隔は不均一）に、スペースが現れています。（スペースが入っていない行は、正しいS/SXSYと思われます＝PC側で割り算して重心を求めて表示させると対象物の重心位置と一致しているっぽい）
[![https://gyazo.com/ab00762c20a1b7163b579153abb36a64](https://gyazo.com/ab00762c20a1b7163b579153abb36a64/raw)](https://gyazo.com/ab00762c20a1b7163b579153abb36a64)

**Comment by watari3** [comment]
仕様を確認したく下記について回答願います。

【仕様確認事項】
- 画像の外枠((0,0)-(639,0)-(639,479)-(0,479)で囲まれる四角形の外側)に何らかの線を表示する必要があるか
→オリジナルは黒線を表示
- 重心を中心に上下1ピクセル、つまり3x3ピクセルの四角形部分を黒色にする必要があるか
→オリジナルは3x3ピクセルの黒四角を表示
- 重心を中心に赤十字(横方向640ピクセルの線と縦方向480ピクセルの線。交点は重心)のカーソルを表示
→今回実装(バグを修正すること)
- カーソルはdigitize/rawとも表示する
→オリジナルはdigitize時のみ

**Comment by akita11** [comment]
>
>
>    - 画像の外枠((0,0)-(639,0)-(639,479)-(0,479)で囲まれる四角形の外側)に何らかの線を表示する必要があるか
>    →オリジナルは黒線を表示
>
>
どちらでもよいです（あってもなくてもよい）


>
>    - 重心を中心に上下1ピクセル、つまり3x3ピクセルの四角形部分を黒色にする必要があるか
>    →オリジナルは3x3ピクセルの黒四角を表示
>
>  ↓の赤十字が表示されるのであれば、不要です（あってもOK）


>    - 重心を中心に赤十字(横方向640ピクセルの線と縦方向480ピクセルの線。交点は重心)のカーソルを表示
>    →今回実装(バグを修正すること)
>
>
これを要望します。


>
>    - カーソルはdigitize/rawとも表示する
>    →オリジナルはdigitize時のみ
>
>
両方とも表示、でお願いします。

**Comment by watari3** [comment]
カーソル表示するようRTLを変更しました。

またASCII形式の16進数に対してエラー検出回路を作りましたがデバッグ出来ていません。
TOP層のrslt_*_ffがそれに当たります。
実機確認する際この信号を含めて観測していただけないでしょうか。

**Comment by akita11** [comment]
えと、「エラー検出回路」を入れてエラーが起こったら回避するのではなく、本来は起こらないはずのエラー（0-9/A-F以外の文字が送られたら）の原因を摘む、のが順当ではないかと思うのですが、いかがでしょう。この「エラー」は、以前（HostIFを入れる前のあたりまで）には起こっていなかった現象ですので。

あと実機確認する際に観測するべき信号をおしえてください。

**Comment by watari3** [comment]
説明し直します。
「エラー検出回路」はあくまでエラー検出であってエラーの原因を掴むためのものです。
一応コードを書きましたが時間切れで十分なSimulationが出来ていません。
このことを「デバッグ出来ていません」と表現しました。

TOP層に下記信号があります。

- rslt_s_ff
- rslt_sx_ff
- rslt_sy_ff
- rslt_qsx_ff
- rslt_qsy_ff

それぞれS, SX, SY, QSX, QSYのIsXDIGIT(16進数のキャラクタかどうか判定する信号)結果になります。
現状Simulationしていないのと等価なのであまりあてになりませんが何かありましたらこの信号を観測ください。

**Comment by akita11** [comment]
ああなるほど。そういう意味ですね。わかりました。この5つの信号を観測するだけでよいですか？

**Comment by watari3** [comment]
6/22 AM 7:00頃のRTLであればrslt_s_ff, rslt_sx_ff, rslt_sy_ffをILAに結線してあります。
エラーの症状に合わせて接続していただけないでしょうか。

自信がないのでIsXDIGITを含むエラー検出回路が動作していないかもしれませんが...

**Comment by akita11** [comment]
素朴な疑問なのですが、以前除算器を入れる前のときには、S/SX/SYは正常（このようにとこどころこ空白などは入らなかった）でしたよね。
で、その後除算器を入れたわけですが、いまUARTでみているのはS/SX/SYの値なので、除算器の動作とは無関係なはず、ですよね。
ということは、S/SX/SYにこのような空白などが入る現象の原因が理解できないのですが、これは起こりうることなのでしょうか（原因のめどはありますか）？

**Comment by watari3** [comment]
記録の為に記載します。

演算回路のクロックとUARTの出力回路のクロックは非同期です。また発生している症状からバス信号の受け渡しをミスしている様にみえます。
このエラーが発生した時のある信号の位相関係が分かれば対策出来ると思っています。
おおよそこれだろうという信号の目星はついていますので裏取りしたい、という事になります。

**Comment by akita11** [comment]
的を外しているかもしれませんが、送信データをダブルバッファ構成にすれば解決されたりしませんか？（つまり送信中に結果の書き込みがおこっても大丈夫なように）

また原因がそれなのであれば、以前から起こっていたはずですよね（私が見落としていただけ？）

**Comment by akita11** [comment]
動作確認してみました。カーソル表示、S/SX/SYのところどころの文字化け、いずれもOKそうです。
1点だけ確認をさせてください。OUT_SEL=1としてS/QX/QYをUART出力しているときのそれぞれのビット数は、OUT_SEL=0でS/SX/SYのときと同じでしょうか。とすると、QX/QYは整数部分のみの出力、でしょうか。（ちなみにですが、これを小数部を含む書式に変更することは、けっこう手間でしょうか？）

**Comment by watari3** [comment]
動作検証し問題ないことが確認されたので本件 close
上記の質問に対しては issue #23 にて回答する。
