### ISSUE TITLE
UART対応

### ISSUE THREAD

**Issue by watari3** [akita11/EyeTracker#3]
UART対応として以下の機能を実装する。
機能排他とするため、外部JPなどで切り替えを行う。

・内部レジスタアクセス制御(UART Tx, Rx使用)
・重心結果のみ出力

**Comment by watari3** [comment]
UART回路としてUART_RX_CORE.v UART_TX_CORE.vを追加

上位層の回路作成必要

**Comment by watari3** [comment]
上記「重心結果のみ出力」を実装済み。

**Comment by akita11** [comment]
直接は関係ありませんが、TXとRXのピン番号指定が逆だったので、修正しておきました。

**Comment by watari3** [comment]
改行コードを出力するように修正 (ステートマシーンの記述ミスを修正)

**Comment by akita11** [comment]
UARTの出力で、ちょっと理解に苦しむところがあります。
カメラで撮っている画像や閾値の設定は適当ですので、出てくるS、SX、SYの値そのものは適当な値ということで、その妥当性は無視しています。

ロジアナ波形で、このような部分があります。
[![https://gyazo.com/c8862d6567a1025ee2c8042e34d7b192](https://gyazo.com/c8862d6567a1025ee2c8042e34d7b192/raw)](https://gyazo.com/c8862d6567a1025ee2c8042e34d7b192)

(1)この付近では、uart_dataに0x30があることから、これが送られているはずで、7bit/no parity/1stop
 bitだと、出力ビット列は、0 0000110 1、となるはずです。（最初の0がstart、最後の1がstop、その間の7bitが0x30）つまりこの青と黄のマーカの間隔は1bit分の時間ということになります。この青と黄のマーカの間隔は、この横軸では4519-4308=211ですが、オシロで計測すると9.2usとなっています。これは約115200bpsに相当しますが、ビットレートはその2倍の230400bps、のはずですよね。（つまりビットレートが115200bpsなのではないか？という推測）

(2)この付近で送っているデータ(uart_data)がこちら。
[![https://gyazo.com/12f9d4440daaff94c023dea70940d3e7](https://gyazo.com/12f9d4440daaff94c023dea70940d3e7/raw)](https://gyazo.com/12f9d4440daaff94c023dea70940d3e7)
これをみると、20個の0x30のあと、0x00が送られています。
この0x00あたりを拡大したのがこちら。
[![https://gyazo.com/f84224e4b8483ba73014358125dee683](https://gyazo.com/f84224e4b8483ba73014358125dee683/raw)](https://gyazo.com/f84224e4b8483ba73014358125dee683)

0x30のあと、一瞬0xffになったあと、0x00になっています。
仕様では、区切りは0x0d、と記憶していますが、これはバグでしょうか。
（115200bps/7bit/no parity/1stopでPCで受信すると、たしかに0x30が19個＋0x00、を繰り返しています）

(3)そもそも論なのですが、UARTで出てくるデータのフォーマットを教えてください。
Sが20bit、SXとSYが28bitなので、それらを16進表記すると、それぞれ5文字と7文字。あわせて19文字になりますが、これをつなげた19文字の'0'-'9'/'A'-'F'のキャラクタが送られてきますか？（上記データが0x30、つまりキャラクタでは'0'なので、この仕様ではないかと推測しています）この推測が正しいとすると、19バイト＋区切りの1バイト=20バイトが1フレーム分のデータ、ということになりますか？（この推測は、(2)で0x30が19個続くことと整合性がとれている）

**Comment by akita11** [comment]
↑こちら、別便のメールで連絡をいただいていた、更新を反映させる前のものでした。失礼しました。これから反映させて試してみます。

**Comment by akita11** [comment]
↑↑昨日の朝いただいた最新のリポジトリ(2017/5/28 20:14)をpullして書き込んでみました。
UARTから出てくるのは、230400bpsになりましたが、やはり19個の0x30＋0x00、の繰り返しです。
↑↑の(2)と(3)、確認＆情報ください。

**Comment by watari3** [comment]
症状の確認をしたいと思います。
お手数ですが下記をご対応いただけないでしょうか。

1) JPのピン配置及び設定は適切か、
2) 改行コードが出力されていない、とは0x0Dが出力されていないとのことか。0x0A(LF)を出力する仕様ではなく0x0D(CR)を出力する仕様に変更すべきか。それとも0x0D, 0x0Aと出力すべきか。
3) TOP.vの後ろの記述を以下に変更しsum_sを観測しsum_sが0以外となっているか。
        .probe18(sum_s[7:0]/*VGA_R*/),
        .probe19(sum_s[8]/*clk_uart_x8*/),
        .probe20(sum_s[9]/*start_trig*/),
        .probe21(sum_s[10]/*uart_de*/),
        .probe22(sum_s[18:11]/*uart_data*/),
        .probe23(sum_s[19]/*tx_busy*/) /*,*/
4) vgaout_modeを0にした場合sum_sなどUARTの出力値が現在の結果から変化するか。

現在JP設定を疑っています。
またUARTの方は仕様の確認ということで質問しています。

ご対応いただければ幸いです。

**Comment by watari3** [comment]
【仕様】
・sum_s(5キャラクタ)sum_sx(7キャラクタ)sum_sy(7キャラクタ)改行コード(1キャラクタ)
【バグ】
・改行コードが0x0と出力される。
・改行コードは0x0D
【対応方法】
・UART_IF.v/310行目 LSB側に詰めて設定しているものをMSB側に詰める様修正する必要あり
→next_hold_data  <= {8'h0A, 48'h0 };の様に修正 (改行コードに合わせて8'h0Aを変更すること。2キャラクタ出力する場合は330行目のnext_wait_count <= 'h1 - 'h1;の前半の'h1を変更すること。)

帰宅後にコードをコミットします。

**Comment by akita11** [comment]
UART出力データの仕様→理解しました（確認ですが16進表記の5/7キャラクタ、ですよね？）。出てくるデータは上のほうに書いたのですが、改行コードと思われるところに0x00が出てきています。改行コードは、0x0aでも0x0dでも、その2つ、でもかまいません（PC側であわせます）。現行の仕様が0x0aのみ、なので、対応方法のところを読むと、0x0aの1バイトのまま、とするのがよさそうですね。↑の対応方法、というのを試してみたいと思います。

1.JPピン→上記の通り、適当(not 適切)に設定しています（本来はVGAOUT=0として二値化の状況を確認しながらJPを設定すべきですが、現在行っている動作チェックは、(a)生画像出力（これはOK）、(b)UARTから出てくる値のフォーマットの確認（19バイトの16進数文字＋改行コード、が出ているか。これは↑のとおり改行コードのところに0x00が出てきている）、です。S/SX/SYの値が、正しいかどうか、は、いまは気にしていません（正しい値を得るためにはJPを適切に設定する必要があるが、いまはそれ以前の段階）。
3.4.は、これからやってみます。

**Comment by akita11** [comment]
↑の件、UART_IF.vに「対応方法」の修正を行い、改行コード0x0aが20バイトごとに出てくることは確認できました。
S/SX/SYの値はすべて'0'(0x30)となっていますが、これはJPの閾値の設定が不適切なのが原因と思われるので、引き続き調整してみます。

**Comment by akita11** [comment]
JPの設定の件、原因がわかった気がします。状況確認とあわせて、読んでください。
まず確認ですが、vgaout_mode=0(digitized)のときは、JPで設定した閾値より明るい画素が"1"、それ以外の画素が"0"となって、VGA出力では、それに応じた二値画像が表示される、という動作という理解でよろしいですね？

で、ボードの回路図をみていただくとわかるのですが、JP[7:0]は、ショートピンをおくと3Vにつながるようになっています。つまりショートピンがない状態では0になるようにプルダウンされるべき信号です。
TOP_implement.tclでは、
`set_property PULLUP TRUE [get_ports [list JP[*]]]`
と書いてあるので、これを
`set_property PULLDOWN TRUE [get_ports [list JP[*]]]`
とすれば、プルダウンになって、ショートピンなし=0、あり=1、となるはずですよね。

で、このように書き換えてimplementをしてみたのですが、ショートピンがないピンが"1"のまま、で、プルダウンが効いていないっぽいです。
implementのレポート（以下）でピン配置結果をみると、PULLUPもPULLDOWMの指定されているっぽいところがないのですが、本来は、正しくPULLUP/DOWNが設定されると、このレポートのどこに出てくるか、わかりますか？（＝ここどこにもPULLUP/DOWNが出てこないのでTOP_implement.tclでのPULLUP/DOWNの指定の仕方が違うのではないか？と疑っている）
[![https://gyazo.com/8e10e026e17eaf88f6508655af95fedd](https://gyazo.com/8e10e026e17eaf88f6508655af95fedd/raw)](https://gyazo.com/8e10e026e17eaf88f6508655af95fedd)

**Comment by akita11** [comment]
↑の件、ImplementationのI/O planningでみると、JP[7:0]がPULLUP指定のままで、ここからPULLDOWNに指定できそうなので、やってみます。このTOP_implement.tclを明示的に読み込みなおす、とやらないと、反映されないんですかね。

**Comment by akita11** [comment]
↑のPULLDOWN指定はうまくいきました（書き込んで、JPが、ショートピンなし＝"0"、あり＝"1"にできるようになった）。ただvgaout_mode=0(digitize)のときのVGAモニタに映る映像が、前面グレーのまま、です（中央やや下の左寄りに黒い四角が1個だけ現れる：以下の画像）。これはJPの設定をいろいろ変えてみましたが、映る映像は変わりません。
https://www.dropbox.com/s/yb3d01o3ajafzfo/2017-05-30%2012.58.50.jpg?dl=0

カメラに映している映像は、黒いところも明るいところもそれなりにある映像です（以下）。なおこの映像が、上のほうの細長い領域しか映っていないのは、仕様（カメラでそう設定している）で正しい現象です。
https://www.dropbox.com/s/p3v4wqy6yj755lb/2017-05-30%2012.58.05.jpg?dl=0

**Comment by akita11** [comment]
（自分への備忘録）VGAout.vを読んで、vgaout_mode=0(digitize)のときのVGA出力が、画素ごとにフラグ=1→0xc0、フラグ=0→0x00、となるのは理解しました。ここですね。
```
    assign  mem_dat = (iVGAout_mode==1'b0) ? {sel_memout_0, sel_memout_0, 6'b000000}: 
                                             {sel_memout_1, sel_memout_2, sel_memout_3, sel_memout_4, sel_memout_5, 3'b000};

```

**Comment by akita11** [comment]
ILAの.proveで、JPの値を見たりしながら、いろいろいじってみました。わかったこと、おこった現象、をいくつか。
・ロジアナでJP（から設定されているthreshold）の値を読んだところ、ジャンパピンで設定したとおりの値になっていることは確認しました。つまり閾値の設定は正常。
・「重心計算処理」issueに書いたように、本来は重心の計算は黒画素に対して行うので、フラグを立てる条件式の不等号を逆（画素値＜threshold）にしました。vgaout_mode=0(digitize)時に表示される映像は、変化ありません。ただ、ときどき（再現性なし）、ここで、縦縞が出ることとがあります。カメラを動かすと、縦縞が変わったり消えたりします。（出ないときもある）。縦縞は、本当に縦縞で、X方向には何本かのグレー／黒の模様があり、Y方向にはその模様が一直線に続く、つまり画像メモリへのアクセスで、Y方向アドレスが一定になってしまっている、っぽい現象です。
・このときにUARTから出てくる値は、0ではない値のときがありました。ただこれも、画像を変えても変化しなかったり変化したり、と再現性がありません。

上記の変更をcommitしておきました。これらの現象の原因をみていただけますか。必要でしたら実機をお渡しします。

**Comment by watari3** [comment]
Block RAMのWrite Depth/Read Depthの値が原因の可能性あり。

【MEM IPのアップデート手順】
・Project Manager WindowのSources WindowのIP sourceタグをクリック
・IP/MEMで右クリック→Re-customize IPを選択
・Port A Optionsタブを選択しWrite Depthを512から1024に変更
・OKをクリックしIPを再生成(Out of context per IP)

上記の手順でMEM.v(BRAM)を修正いただけないでしょうか。

こちらも同様の手順でデザインのアップデート、論理合成&配置配線を実行中です。

**Comment by akita11** [comment]
こちら、いまやっています。

**Comment by akita11** [comment]
↑の修正、やってみました。現象としては変化がありません。いくつか記録。
・生画像出力(vgaout_mode=1)では、特に問題なさそうに、カメラからの映像がモニタに表示される
・digitizeモード(vgaout_mode=0)では、最初縦縞。カメラに映る映像を変化させるとグレー一色（一箇所だけ黒点あり）。UARTから出てくるS/SX/SYの値は、この両者で別の値にはなっている（その値が正しいかは検証していない）。

**Comment by akita11** [comment]
↑の件、その後いろいろ調べているのですが、理解に苦しんでいます。
CLctrl.vを見る限り、生画像も二値化後の画像も、同じようにメモリに書き込んでいて、
VGAoutのほうで、vgaout_modeに応じて、生画像または二値化画像を読みだしてDACへ出力していますよね。
ということは、生画像が問題なく表示されている（＝メモリへの読み書きとDAC出力はOK）ということは、二値化画像も、同じように問題なく表示されるはず、と理解しているのですが・・・

**Comment by watari3** [comment]
私も上記の認識と同じです。

上記の件に関して、仕様確認したいことがあります。
以下についてお答えいただけないでしょうか。

【現状の仕様】
1) MEMOUTSELモジュールはVGACLKに同期して動作。その際のselect信号はVGAのタイミング回路で生成
2) カメラ側のビデオデータのSRAMへの書き込みはVGAのタイミング回路で生成されたfield(select)信号を元にVGAのタイミング回路がアクセスしていない方に対してWrite。

【確認事項】
a) 上記の1)と2)の仕様は正しいか。なおオリジナルソースに沿って上記を実装。
b) 実は1)は正しく2)はカメラ側のタイミングでWrite処理を切り替える必要があるのではないか。

**Comment by watari3** [comment]
備忘録を兼ねて記載。

> ただ、ときどき（再現性なし）、ここで、縦縞が出ることとがあります。カメラを動かすと、縦縞が変わったり消えたりします。（出ないときもある）。縦縞は、本当に縦縞で、X方向には何本かのグレー／黒の模様があり、Y方向にはその模様が一直線に続く、つまり画像メモリへのアクセスで、Y方向アドレスが一定になってしまっている、っぽい現象です。

これはダブルバッファメモリへの書き込み制御信号を出力側のVGAのタイミング生成回路の信号を使用していることに起因していそうです。カメラ側で必要な信号(*1)を作りそれを元に動くよう変更すれば挙動が変わるような気がします。これについては一つ前の投稿の確認事項と関連します。仕様が明確になればこの問題が解決しそうですが...

*1)
カメラ側のフレームの切り替わりをトリガーに重心処理を行っているので、このタイミングでフレームの切り替わり信号（トグル信号）を生成する。

**Comment by akita11** [comment]
上記(2)は、オリジナルがそんな実装になっていましたか・・・これは確かにおかしいですね。
あくまでも動作（field切り替えとメモリへの書き込みと重心計算）の基準はカメラ側のクロックで行われるべきで、VGA出力（メモリの読出し）は、どちらかのフィールド（固定でもいい）、でOKです。書き込みと読出しが非同期ですが、VGA出力はあくまでも目視確認用なので、VGA出力（読出し）中にカメラ側からの書き込みがはじまって、VGA出力映像が途中から、前のフィールドと次のフィールドが混在しても、まったく問題ありません。
つまり上記*1)とするように変更すべきです。

**Comment by akita11** [comment]
あとUARTのピン配置。SC2_pin.xlsの記載がちょっとまぎらわしいのですが、
信号名、FPGAピン、つなぐべきFTDI-Basicピン、の順に、
TX(FPGAの出力)、W16、2(RXi)
RX(FPGAの入力)、U17、3(TXo)
GND、-、5

**Comment by watari3** [comment]
UARTによるHost I/Fを実装

issue #17 のcloseと同時に本件もcloseする予定

**Comment by watari3** [comment]
issue #17 をcloseしたので本件もclose
